collections:
  products:
    output: true
  articles:
    output: true
    permalink: /articles/:title/

_inputs:
  layout:
    hidden: true

_select_data:
  positions:
    img-left: Left
    img-left-center: Left Centre
    img-center: Centered
    img-right-center: Right Centre
    img-right: Right
